name: lico-auditor-release-gate

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
      - "*-v*.*.*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lico-auditor:
    uses: LicoLand/Lico-Auditor/.github/workflows/release-audit.yml@only
